import {createWorkbenchClient} from '../api/workbench-client.js';
import {PROVIDERS,RUNTIME_SCENARIOS,initialState,providerPresentation,reduceWorkbench} from '../features/workbench/workbench-state.js';
const client=createWorkbenchClient(); let state=initialState; let config;
const byId=id=>document.getElementById(id);
const elements={project:byId('project'),fixture:byId('fixture'),scan:byId('scan'),message:byId('message'),next:byId('next-action'),result:byId('scan-result'),stateBadge:byId('state-badge'),evidenceBadge:byId('evidence-badge'),providers:byId('providers')};
function textOption(select,value,label){const item=document.createElement('option');item.value=value;item.textContent=label;select.append(item);}
function render(){elements.message.textContent=state.message;elements.next.textContent=state.nextAction;elements.stateBadge.textContent=state.state.replace('_',' ');elements.stateBadge.className=`badge ${['ERROR','BLOCKED','PERMISSION_DENIED','QUOTA','CANCEL'].includes(state.state)?'danger':'neutral'}`;elements.evidenceBadge.textContent=state.evidence.badge.replace('_',' ');elements.evidenceBadge.className=`badge ${state.evidence.badge==='FIXTURE'?'fixture':'neutral'}`;elements.scan.disabled=!config||state.state==='LOADING';elements.result.replaceChildren();if(state.scan){const list=document.createElement('dl');for(const [label,value] of [['상태',state.scan.status],['브랜치',state.scan.repository.branch||'없음'],['언어',state.scan.repository.language||'미확인'],['Dirty path',String(state.scan.repository.trackedDirtyPaths)],['무변경 증명',state.scan.noWriteIdentical?'IDENTICAL':'REJECTED']]){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;row.append(dt,dd);list.append(row);}elements.result.append(list);}else elements.result.textContent='아직 실행되지 않았습니다.';for(const button of elements.providers.children){const view=providerPresentation(state,button.textContent);button.disabled=view.disabled;button.setAttribute('aria-checked',view.ariaChecked);}}
async function boot(){try{config=await client.config();textOption(elements.project,config.project.projectId,config.project.name);for(const fixture of config.fixtures)textOption(elements.fixture,fixture.fixtureId,fixture.label);state=reduceWorkbench(state,{type:'SELECTION_CHANGED',projectId:elements.project.value,fixtureId:elements.fixture.value});render();}catch{state=reduceWorkbench(state,{type:'SCAN_FAILED',state:'ERROR',message:'설정을 불러오지 못했습니다.'});render();}}
elements.scan.addEventListener('click',async()=>{state=reduceWorkbench(state,{type:'SCAN_STARTED'});render();try{const payload=await client.scan({projectId:elements.project.value,fixtureId:elements.fixture.value,role:'operator',csrfToken:config.csrfToken});state=reduceWorkbench(state,{type:'SCAN_RECEIVED',payload});}catch(error){state=reduceWorkbench(state,{type:'SCAN_FAILED',state:error.state||'ERROR',message:error.message});}render();});
for(const provider of PROVIDERS){const button=document.createElement('button');button.type='button';button.textContent=provider;button.setAttribute('role','radio');button.setAttribute('aria-checked','false');button.disabled=true;button.addEventListener('click',()=>{state=reduceWorkbench(state,{type:'PROVIDER_SELECTED',provider});render();});elements.providers.append(button);}
const runtimeActions=document.createElement('div');runtimeActions.id='runtime-actions';runtimeActions.setAttribute('role','group');runtimeActions.setAttribute('aria-label','Fixture runtime state');
for(const runtimeState of Object.keys(RUNTIME_SCENARIOS)){const button=document.createElement('button');button.type='button';button.textContent=`${runtimeState} fixture`;button.dataset.runtimeState=runtimeState;button.addEventListener('click',()=>{state=reduceWorkbench(state,{type:'RUNTIME_STATE_SELECTED',state:runtimeState});render();});runtimeActions.append(button);}
document.querySelector('.registration').append(runtimeActions);
elements.fixture.addEventListener('change',()=>{state=reduceWorkbench(state,{type:'SELECTION_CHANGED',projectId:elements.project.value,fixtureId:elements.fixture.value});render();});
render();boot();
