import {createWorkbenchClient} from '../api/workbench-client.js';
import {PROVIDERS,RUNTIME_SCENARIOS,initialState,providerPresentation,reduceWorkbench,createProductionState,mapHttpFailure,normalizeProviderCatalog,normalizeProviderDetail,normalizeSessionStatus,reduceProductionWorkbench} from '../features/workbench/workbench-state.js';

const client=createWorkbenchClient();
const byId=id=>document.getElementById(id);
const text=(parent,label,value)=>{const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;row.append(dt,dd);parent.append(row);};

function bootFixture(){
  let state=initialState;let config;
  const elements={project:byId('project'),fixture:byId('fixture'),scan:byId('scan'),message:byId('message'),next:byId('next-action'),result:byId('scan-result'),stateBadge:byId('state-badge'),evidenceBadge:byId('evidence-badge'),providers:byId('providers')};
  const option=(select,value,label)=>{const item=document.createElement('option');item.value=value;item.textContent=label;select.append(item);};
  const render=()=>{elements.message.textContent=state.message;elements.next.textContent=state.nextAction;elements.stateBadge.textContent=state.state.replace('_',' ');elements.stateBadge.className=`badge ${['ERROR','BLOCKED','PERMISSION_DENIED','QUOTA','CANCEL'].includes(state.state)?'danger':'neutral'}`;elements.evidenceBadge.textContent=state.evidence.badge.replace('_',' ');elements.evidenceBadge.className=`badge ${state.evidence.badge==='FIXTURE'?'fixture':'neutral'}`;elements.scan.disabled=!config||state.state==='LOADING';elements.result.replaceChildren();if(state.scan){const list=document.createElement('dl');for(const [label,value] of [['상태',state.scan.status],['브랜치',state.scan.repository.branch||'없음'],['언어',state.scan.repository.language||'미확인'],['Dirty path',String(state.scan.repository.trackedDirtyPaths)],['무변경 증명',state.scan.noWriteIdentical?'IDENTICAL':'REJECTED']])text(list,label,value);elements.result.append(list);}else elements.result.textContent='아직 실행되지 않았습니다.';for(const button of elements.providers.children){const view=providerPresentation(state,button.textContent);button.disabled=view.disabled;button.setAttribute('aria-checked',view.ariaChecked);}};
  const boot=async()=>{try{config=await client.config();option(elements.project,config.project.projectId,config.project.name);for(const fixture of config.fixtures)option(elements.fixture,fixture.fixtureId,fixture.label);state=reduceWorkbench(state,{type:'SELECTION_CHANGED',projectId:elements.project.value,fixtureId:elements.fixture.value});render();}catch{state=reduceWorkbench(state,{type:'SCAN_FAILED',state:'ERROR',message:'설정을 불러오지 못했습니다.'});render();}};
  elements.scan.addEventListener('click',async()=>{state=reduceWorkbench(state,{type:'SCAN_STARTED'});render();try{const payload=await client.scan({projectId:elements.project.value,fixtureId:elements.fixture.value,role:'operator',csrfToken:config.csrfToken});state=reduceWorkbench(state,{type:'SCAN_RECEIVED',payload});}catch(error){state=reduceWorkbench(state,{type:'SCAN_FAILED',state:error.state||'ERROR',message:error.message});}render();});
  for(const provider of PROVIDERS){const button=document.createElement('button');button.type='button';button.textContent=provider;button.setAttribute('role','radio');button.setAttribute('aria-checked','false');button.disabled=true;button.addEventListener('click',()=>{state=reduceWorkbench(state,{type:'PROVIDER_SELECTED',provider});render();});elements.providers.append(button);}
  const runtimeActions=document.createElement('div');runtimeActions.id='runtime-actions';runtimeActions.setAttribute('role','group');runtimeActions.setAttribute('aria-label','Fixture runtime state');for(const runtimeState of Object.keys(RUNTIME_SCENARIOS)){const button=document.createElement('button');button.type='button';button.textContent=`${runtimeState} fixture`;button.dataset.runtimeState=runtimeState;button.addEventListener('click',()=>{state=reduceWorkbench(state,{type:'RUNTIME_STATE_SELECTED',state:runtimeState});render();});runtimeActions.append(button);}document.querySelector('.registration').append(runtimeActions);
  elements.fixture.addEventListener('change',()=>{state=reduceWorkbench(state,{type:'SELECTION_CHANGED',projectId:elements.project.value,fixtureId:elements.fixture.value});render();});render();boot();
}

function bootProduction(){
  let state=createProductionState();
  const elements={auth:byId('auth-status'),badge:byId('state-badge'),message:byId('message'),retry:byId('retry'),providers:byId('providers'),detailTitle:byId('detail-title'),detail:byId('provider-detail'),runId:byId('run-id'),connect:byId('connect-stream'),streamState:byId('stream-state'),lastEventId:byId('last-event-id'),streamMessage:byId('stream-message')};
  const render=()=>{elements.auth.textContent=state.auth.authenticated?`${state.auth.mode} · ${state.auth.actorRole}`:`${state.auth.mode} · NOT AUTHENTICATED`;elements.badge.textContent=state.phase.replaceAll('_',' ');elements.badge.className=`badge ${['ERROR','BLOCKED','AUTHENTICATION_REQUIRED','PERMISSION_DENIED','RECONNECT'].includes(state.phase)?'danger':'neutral'}`;elements.message.textContent=state.message;elements.retry.disabled=state.phase==='LOADING';elements.providers.replaceChildren();for(const provider of state.providers){const button=document.createElement('button');button.type='button';button.className='provider-status';button.setAttribute('role','listitem');button.setAttribute('aria-pressed',String(state.selectedId===provider.id));button.dataset.providerId=provider.id;button.append(Object.assign(document.createElement('strong'),{textContent:provider.displayName}),Object.assign(document.createElement('span'),{textContent:provider.primary?'PRIMARY':provider.status}),Object.assign(document.createElement('span'),{textContent:`Credential ${provider.credentialStatus}`}),Object.assign(document.createElement('span'),{textContent:`Health ${provider.healthStatus}`}),Object.assign(document.createElement('span'),{textContent:`Models ${provider.modelsStatus}`}));button.addEventListener('click',()=>selectProvider(provider.id));elements.providers.append(button);}elements.detail.replaceChildren();if(state.detail){elements.detailTitle.textContent=state.detail.displayName;text(elements.detail,'상태',state.detail.status);text(elements.detail,'Credential',state.detail.credentialStatus);text(elements.detail,'Health',state.detail.healthStatus);text(elements.detail,'Latency',state.detail.latencyMs===null?'NOT AVAILABLE':`${state.detail.latencyMs} ms`);text(elements.detail,'Last error',state.detail.lastError??'NOT AVAILABLE');text(elements.detail,'Models',state.models?.length?state.models.join(', '):'NOT AVAILABLE');}else elements.detailTitle.textContent=state.selectedId?`${state.selectedId.toUpperCase()} 로딩 중`:'Provider를 선택하세요';elements.streamState.textContent=state.phase==='RECONNECT'?'RECONNECT':state.lastEventId?'CONNECTED':'NOT CONNECTED';elements.lastEventId.textContent=state.lastEventId||'NOT AVAILABLE';elements.streamMessage.textContent=state.streamMessage;};
  const selectProvider=async providerId=>{state=reduceProductionWorkbench(state,{type:'PROVIDER_SELECTED',providerId});render();try{const [detailPayload,modelsPayload]=await Promise.all([client.provider(providerId),client.models(providerId)]);const detail=normalizeProviderDetail(detailPayload,providerId);const models=modelsPayload?.data;if(!models||models.provider_id!==providerId||!Array.isArray(models.models)||typeof models.moa_eligible!=='boolean')throw new Error('Invalid provider response');state=reduceProductionWorkbench(state,{type:'DETAIL_RECEIVED',detail,models:[...models.models]});}catch(error){state=reduceProductionWorkbench(state,{type:'LOAD_FAILED',failure:mapHttpFailure(error.status)});}render();};
  const load=async()=>{state=reduceProductionWorkbench(state,{type:'LOAD_STARTED'});render();try{const status=normalizeSessionStatus(await client.sessionStatus());state=reduceProductionWorkbench(state,{type:'AUTH_STATUS_RECEIVED',status});if(!status.authenticated){const error=new Error('Authentication required');error.status=401;throw error;}const providers=normalizeProviderCatalog(await client.providers());state=reduceProductionWorkbench(state,{type:'PROVIDERS_RECEIVED',providers});render();if(state.selectedId)await selectProvider(state.selectedId);}catch(error){state=reduceProductionWorkbench(state,{type:'LOAD_FAILED',failure:mapHttpFailure(error.status)});render();}};
  elements.retry.addEventListener('click',load);elements.connect.addEventListener('click',async()=>{const runId=elements.runId.value.trim();if(!runId){elements.streamMessage.textContent='Run ID를 입력하세요.';return;}elements.streamState.textContent='LOADING';try{const result=await client.runEvents(runId,state.lastEventId);state=reduceProductionWorkbench(state,{type:'STREAM_CONNECTED',...result});}catch{state=reduceProductionWorkbench(state,{type:'STREAM_DISCONNECTED'});}render();});render();load();
}

if(document.body.hasAttribute('data-fixture-workbench')) bootFixture(); else bootProduction();
